// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvE.DAL.Data;

namespace MvE.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("MvE.DAL.Models.CharacterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Acrobatics");

                    b.Property<string>("Alignment");

                    b.Property<int>("AnimalHandling");

                    b.Property<int>("Arcana");

                    b.Property<int>("Athletics");

                    b.Property<string>("Background");

                    b.Property<int>("Charisma");

                    b.Property<int>("CharismaModifier");

                    b.Property<int>("CharismaSave");

                    b.Property<string>("Class");

                    b.Property<int>("Constitution");

                    b.Property<int>("ConstitutionModifier");

                    b.Property<int>("ConstitutionSave");

                    b.Property<int>("Deception");

                    b.Property<int>("Dexterity");

                    b.Property<int>("DexterityModifier");

                    b.Property<int>("DexteritySave");

                    b.Property<int>("History");

                    b.Property<int>("HitDie");

                    b.Property<int>("Initiative");

                    b.Property<int>("Insight");

                    b.Property<int>("Intelligence");

                    b.Property<int>("IntelligenceModifier");

                    b.Property<int>("IntelligenceSave");

                    b.Property<int>("Intimidation");

                    b.Property<int>("Investigation");

                    b.Property<int>("Level");

                    b.Property<int>("MaxHitPoints");

                    b.Property<int>("Medicine");

                    b.Property<string>("Name");

                    b.Property<int>("Nature");

                    b.Property<int>("PassiveWisdom");

                    b.Property<int>("Perception");

                    b.Property<int>("Performance");

                    b.Property<int>("Persuasion");

                    b.Property<int>("ProficiencyBonus");

                    b.Property<string>("Race");

                    b.Property<int>("Religion");

                    b.Property<char>("Size");

                    b.Property<int>("SleightOfHand");

                    b.Property<int>("Speed");

                    b.Property<int>("Stealth");

                    b.Property<int>("Strength");

                    b.Property<int>("StrengthModifier");

                    b.Property<int>("StrengthSave");

                    b.Property<int>("Survival");

                    b.Property<int>("Wisdom");

                    b.Property<int>("WisdomModifier");

                    b.Property<int>("WisdomSave");

                    b.HasKey("Id");

                    b.ToTable("CharacterSheets");

                    b.HasData(
                        new { Id = 526055437, Acrobatics = 2, Alignment = "neutralGood", AnimalHandling = 3, Arcana = 6, Athletics = 2, Background = "Sage", Charisma = 17, CharismaModifier = 3, CharismaSave = 5, Class = "Bard", Constitution = 11, ConstitutionModifier = 0, ConstitutionSave = 0, Deception = 5, Dexterity = 15, DexterityModifier = 2, DexteritySave = 4, History = 6, HitDie = 8, Initiative = 2, Insight = 3, Intelligence = 18, IntelligenceModifier = 4, IntelligenceSave = 4, Intimidation = 3, Investigation = 4, Level = 1, MaxHitPoints = 8, Medicine = 3, Name = "Marvin", Nature = 4, PassiveWisdom = 13, Perception = 3, Performance = 5, Persuasion = 5, ProficiencyBonus = 2, Race = "Human", Religion = 4, Size = 'm', SleightOfHand = 2, Speed = 30, Stealth = 2, Strength = 15, StrengthModifier = 2, StrengthSave = 2, Survival = 3, Wisdom = 16, WisdomModifier = 3, WisdomSave = 3 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
